default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= SENSITIVE.database[:name]%>
  username: <%= SENSITIVE.database[:username]%>
  password: <%= SENSITIVE.database[:password]%>

test:
  <<: *default
  database: <%= SENSITIVE.database[:name]%>
  username: <%= SENSITIVE.database[:username]%>
  password: <%= SENSITIVE.database[:password]%>

production:
  <<: *default
  database: <%= SENSITIVE.database[:name]%>
  username: <%= SENSITIVE.database[:username]%>
  password: <%= SENSITIVE.database[:password]%>
