development:
  database:
    name: "dev_db_name"
    username: "dev_db_username"
    password: "dev_db_password"
test:
  database:
    name: "test_db_name"
    username: "test_db_username"
    password: "test_db_password"
production:
  database:
    name: "prod_db_name"
    username: "prod_db_username"
    password: "prod_db_password"